Running cxxtest tests (13 tests)
In NullCreate::<no test>:
Exceptions.h:10: Error: Test failed: createSuite() failed
Exceptions.h:10: Error: Assertion failed: suite() != 0
In ThrowCreate::<no test>:
Exceptions.h:22: Error: Test failed: Exception thrown from createSuite()
Exceptions.h:22: Error: Expected (createSuite()) not to throw, but it did
Exceptions.h:22: Error: Test failed: createSuite() failed
Exceptions.h:22: Error: Assertion failed: suite() != 0
.
In ThrowDestroy::<no test>:
Exceptions.h:35: Error: Test failed: destroySuite() failed
Exceptions.h:35: Error: Expected (destroySuite()) not to throw, but it did
In ThrowSetUp::testNothing:
Exceptions.h:46: Error: Test failed: Exception thrown from setUp()
Exceptions.h:46: Error: Expected (suite()->setUp(); ok=true) not to throw, but it did
In ThrowTearDown::testNothing:
Exceptions.h:55: Error: Test failed: Exception thrown from tearDown()
Exceptions.h:55: Error: Expected (suite()->tearDown()) not to throw, but it did
In TestThrowFromTest::testThrowSomething:
Exceptions.h:61: Error: Test failed: Exception thrown from test
In TestThrowFromTest::testMoveOn:
Exceptions.h:68: Trace: One failed test doesn't affect the others
.
In DynamicAbort::test_Abort_on_fail_in_this_test:
DynamicAbort.h:8: Error: Expected (1 == 2), found (1 != 2)
DynamicAbort.h:9: Error: Expected (2 == 3), found (2 != 3)
In DynamicAbort::test_Dont_abort_in_this_test:
DynamicAbort.h:15: Error: Expected (1 == 2), found (1 != 2)
DynamicAbort.h:16: Error: Expected (2 == 3), found (2 != 3)
In DynamicAbort::test_Revert_to_abort:
DynamicAbort.h:21: Error: Expected (1 == 2), found (1 != 2)
DynamicAbort.h:22: Error: Expected (2 == 3), found (2 != 3)
In SetUpWorksAllTests::test_Dont_abort_in_this_test:
DynamicAbort.h:36: Error: Expected (1 == 2), found (1 != 2)
DynamicAbort.h:37: Error: Expected (2 == 3), found (2 != 3)
In SetUpWorksAllTests::test_Dont_abort_in_this_test_either:
DynamicAbort.h:42: Error: Expected (1 == 2), found (1 != 2)
DynamicAbort.h:43: Error: Expected (2 == 3), found (2 != 3)
In SetUpWorksAllTests::test_Override_in_this_test:
DynamicAbort.h:49: Error: Expected (1 == 2), found (1 != 2)
Failed 12 and Skipped 0 of 13 tests
Success rate: 7%
Error level = 12
